apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ack-node-problem-detector-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ack-node-problem-detector-role
subjects:
- kind: ServiceAccount
  name: ack-node-problem-detector
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ack-node-problem-detector-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - nodes/status
  - events
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ack-node-problem-detector
  name: ack-node-problem-detector
  namespace: kube-system

