apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /data-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
