apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /data-1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
