apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /data-2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
