{
 "title": "Felix Dashboard (Calico)",
 "description": "This is a work in progress.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active hosts on each node",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "felix_active_local_endpoints", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Felix Dashboard",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 1 },
   "content": "\n# Calico Dashboard (Felix)\n\n\n\n"
  },
  {
   "title": "Felix ipset error counter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(felix_ipset_errors[5m]))"
    }
   ]
  },
  {
   "title": "Felix ipset error counter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(felix_ipset_errors[5m]))"
    }
   ]
  },
  {
   "title": "Felix iptables save errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(felix_iptables_save_errors[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Felix log errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(felix_log_errors[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Felix resync started",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(felix_resyncs_started[5m])) "
    }
   ]
  },
  {
   "title": "Felix cluster policies",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "targets": [
    { "expr": "felix_cluster_num_policies", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active calico nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "targets": [
    { "expr": "max(felix_cluster_num_hosts)", "legendFormat": "Calico node" }
   ]
  },
  {
   "title": "Errors plot",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(felix_ipset_errors[5m])", "legendFormat": "{{instance}} ipset errors" },
    {
     "expr": "rate(felix_iptables_restore_errors[5m])",
     "legendFormat": "{{instance}} iptables restore errors"
    },
    {
     "expr": "rate(felix_iptables_save_errors[5m])",
     "legendFormat": "{{instance}} iptables save errors"
    },
    { "expr": "rate(felix_log_errors[5m])", "legendFormat": "{{instance}} log errors" }
   ]
  },
  { "title": "Dataplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Dataplane apply time quantile 0.5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_int_dataplane_apply_time_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dataplane apply time quantile 0.9",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_int_dataplane_apply_time_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dataplane apply time quantile 0.99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_int_dataplane_apply_time_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}