apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
- token: "9a08jv.c0izixklcxtmnze7"
  description: "kubeadm bootstrap token"
  ttl: "24h"
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: 783bde.3f89s0fje9f38fhf
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: 172.23.70.88
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    cgroup-driver: systemd
skipPhases:
- addon/kube-proxy

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: test1
imageRepository: k8s.gcr.io
kubernetesVersion: 1.23.6
controlPlaneEndpoint: 47.243.249.98:6443
certificatesDir: /etc/kubernetes/pki
apiServer:
  timeoutForControlPlane: 4m0s
  extraArgs:
    enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeClaimResize,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority,TaintNodesByCondition"
    audit-policy-file: "/etc/kubernetes/audit-policy.yaml"
    audit-log-format: "json"
    audit-log-maxage: "30"
    audit-log-path: "/var/log/kube-audit/audit-log.json"
    audit-log-maxbackup: "10"
    audit-log-maxsize: "100"
    service-node-port-range: "30000-32767"
    profiling: "false"
    bind-address: 0.0.0.0
    etcd-servers: "https://172.23.70.88:2379"
    authorization-mode: "Node,RBAC"
    authentication-token-webhook-cache-ttl: 5s
    allow-privileged: "true"
    insecure-port: "0"
    kubelet-preferred-address-types: "InternalIP,Hostname,ExternalIP"
    runtime-config: "authorization.k8s.io/v1beta1=true"
    storage-backend: "etcd3"
    service-account-lookup: "true"
    feature-gates: "RemoveSelfLink=false"
    secure-port: "6443"
    max-mutating-requests-inflight: "800"
    max-requests-inflight: "1500"
  certSANs:
  - 47.243.249.98
  - 10.200.0.1
  - 127.0.0.1
  - 172.23.70.88
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster.local
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: timezone
  - name: audit-policy
    hostPath: /etc/kubernetes/
    mountPath: /etc/kubernetes/
  - name: auditk8-log
    hostPath: /var/log/kube-audit/
    mountPath: /var/log/kube-audit/

controllerManager:
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: timezone
  extraArgs:
    kube-api-qps: "150"
    kube-api-burst: "200"
    node-monitor-grace-period: "40s"
    pod-eviction-timeout: "5m0s"
    profiling: "false"

etcd:
  local:
    imageRepository: k8s.gcr.io
    imageTag: 3.5.3-0
    serverCertSANs:
    - 172.23.70.88
    peerCertSANs:
    - 172.23.70.88

dns:
  imageTag: v1.8.6

networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.200.0.0/16
  podSubnet: 10.100.0.0/16

scheduler:
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: timezone

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDomain: cluster.local
containerLogMaxFiles: 10
containerLogMaxSize: 100Mi
maxPods: 200
podPidsLimit: 16384
staticPodPath: /etc/kubernetes/manifests
logging:
  verbosity: 3
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
cgroupDriver: systemd
rotateCertificates: true
evictionHard:
  imagefs.available: "15%"
  memory.available: "5%"
  nodefs.available: "10%"
  nodefs.inodesFree: "5%"
systemReserved:
  cpu: "100m"
  memory: "1Gi"
  pid: "1000"
  ephemeral-storage: "5Gi"
kubeReserved:
  cpu: "100m"
  memory: "1Gi"
  pid: "1000"
  ephemeral-storage: "5Gi"
nodeStatusUpdateFrequency: 5s
clusterDNS:
- 10.200.0.10
